---
asdf_version: v0.14.0

asdf_install_dir: "{{ ansible_env.HOME }}/.asdf"

asdf_default_shell: "/bin/zsh"

asdf_init_script: "{{ (asdf_default_shell | basename == 'fish') | ternary('asdf.fish', 'asdf.sh') }}"

# List plugins and versions to install.
# asdf_versions:
#   - name: PLUGIN_NAME (required)
#     repo: PLUGIN_REPOSITORY_URL (optional)
#     versions:
#       - 1.0.0
#       - 2.0.0
asdf_versions:
  - name: python
    versions:
      - 3.12.1
      - 3.12.4
