---
- name: "Tmux | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: tmux_distribution_config
- name: "Tmux | Run Install Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: tmux_distribution_config.stat.exists

- name: "Tmux | Install TMP"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"

- name: "Tmux | Configure tmux"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/.dotfiles/.config/tmux"
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
