- name: "LSD | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: lsd_distribution_config

- name: "LSD | Run Install Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: lsd_distribution_config.stat.exists


- name: LSD | Ensure .config/lsd directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/lsd"
    state: directory
    mode: "0755"

- name: LSD | Copy config file
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/.dotfiles/.config/lsd/config.yml"
    dest: "{{ ansible_user_dir }}/.config/lsd/config.yml"
    mode: "0644"
